FROM python:3.12

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 
RUN mkdir /etl
WORKDIR /etl

COPY ./requirements.txt /etl/requirements.txt

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --no-cache-dir --upgrade -r /etl/requirements.txt


CMD ["python", "scheduler.py"]