version: "3.9"
services:
  etl:
    volumes:
      - .:/etl
    build:
      context: .
      dockerfile: ./Dockerfile.etl
    env_file:
      - .env
  calcvars:
    volumes:
      - ./calcvars:/calcvars
    build:
      context: .
      dockerfile: ./Dockerfile.calcvars
    env_file:
      - .env
  neiro-getway:
    volumes:
      - .:/neiro_getway
    build:
      context: .
      dockerfile: ./Dockerfile.neiro_getway
    env_file:
      - .env
  tg-bot:
    volumes:
      - ./tg:/app
    env_file:
      - .env
    build:
      context: ./tg/
      dockerfile: Dockerfile
    depends_on:
      - neiro-getway
      - etl

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450